CREATE TABLE GAB_FIN_STATE_INFO(
ID IDENTITY DEFAULT '0',
STATEMENT_NUM INTEGER,
GROUP_ORDER INTEGER,
SUB_GROUP INTEGER,
TITLE VARCHAR(50),
BEG_ACCOUNT VARCHAR(15),
END_ACCOUNT VARCHAR(15),
FLAG_TOTAL VARCHAR(1),
PRIMARY KEY (ID)
);