CREATE TABLE GAB_FIN_STATE_DTL(
ID IDENTITY DEFAULT '0',
STATEMENT_NUM INTEGER,
GROUP_ORDER INTEGER,
SUB_GROUP INTEGER,
TITLE VARCHAR(50),
CP_AMOUNT NUMERIC(15,0),
CP_PERCENT NUMERIC(4,1),
CY_AMOUNT NUMERIC(15,0),
CY_PERCENT NUMERIC(4,1),
PY_AMOUNT NUMERIC(15,0),
PY_PERCENT NUMERIC(4,1),
PPY_AMOUNT NUMERIC(15,0),
PPY_PERCENT NUMERIC(4,1),
NC_AMOUNT NUMERIC(15,0),
NC_PERCENT NUMERIC(4,1),
NC_PERCENT_COMPARE NUMERIC(4,1),
PRIMARY KEY (ID)
);